using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NatlParkTracker
{
    /// <summary>
    /// This is information about a visit to a park
    /// </summary>
    /// 

    public enum TripType
    {
        Business,
        WithKids,
        Solo,
        Couple,
        Other
    }
    public class Visit
    {
        #region Variables
        private static int lastVisitNumber = 0;
        //private static double 

        #endregion

        #region Properties
        public string Date { get; set; }
        public TripType TripType { get; set; }
        public string TripName { get; set; }
        public int VisitNumber { get; private set; } // number generated by the program with the constructor method
        public string ParkName { get; set; }
        public int DaysSpent { get; set; }
        public string Lodging { get; set; }
        public double VisitTotalSpent { get; private set; }
        public string TripNotes { get; set; }
        #endregion

        #region Constructor // run this method whenever "new visit" is invoked.  this method has no return type, no parameters
        public Visit()     // needs to be public so all can access and must be named the same as the class name.  so when the "new Visit" is called 
        {
            VisitNumber = ++lastVisitNumber;
            
        }  

       
        #endregion

        #region Methods
        public double Spent (double amount)
        {
            VisitTotalSpent += amount;
            return VisitTotalSpent;
        }
        #endregion
    }
}
